### ISSUE TITLE
只能下載第一個影片

### ISSUE THREAD

**Issue by ricks774** [techmovie/hahow-video-downloader#1]
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
开始下载:1-1-課程.mp4
开始下载:1-1-課程.zh-TW.vtt
vtt转srt
格式转换成功,删除1-1-課程.zh-TW.vtt
node:events:505
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open 'D:\課程.zh-TW.vtt'
Emitted 'error' event on ReadStream instance at:
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'D:\\課程.zh-TW.vtt'
}
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------

執行後下載課程中的第一個影片後就結束了，試著更換courseUrl的網址也是都只下載第一個影片
不曉得是否我有哪邊有設定錯誤呢?

**Comment by xheiop** [comment]
可能是生成字幕文件的时候出错了 我这里复现不出来 我先改了一版 你可以测测看

**Comment by ricks774** [comment]
非常感激 不過測試後的情況還是一樣 代碼內容那些也都相同
也許是我這邊少了什麼插件嗎?

**Comment by xheiop** [comment]
> 非常感激 不過測試後的情況還是一樣 代碼內容那些也都相同 也許是我這邊少了什麼插件嗎?

如果执行了 `yarn`这个命令 应该不会少什么插件的 

`D:\課程.zh-TW.vtt` 这个文件存在么？

**Comment by ricks774** [comment]
> 如果执行了 `yarn`这个命令 应该不会少什么插件的
> 
> `D:\課程.zh-TW.vtt` 这个文件存在么？

我看產出資料夾內只有`課程.mp4`跟`課程.srt`檔案

**Comment by ricks774** [comment]
> > 非常感激 不過測試後的情況還是一樣 代碼內容那些也都相同 也許是我這邊少了什麼插件嗎?
> 
> 如果执行了 `yarn`这个命令 应该不会少什么插件的
> 
> `D:\課程.zh-TW.vtt`     ####这个文件存在么？

**Comment by xheiop** [comment]
Node.js的版本的问题 如果是V16.x 需要降级到14.x

**Comment by ricks774** [comment]
> Node.js的版本的问题 如果是V16.x 需要降级到14.x

Node.js降到14版本後可以順利下載了 非常感謝!!!

**Comment by ricks774** [comment]
开始下载:5-3-課程.mp4
events.js:353
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open 'D:\hahow-video-downloader-main\課程.mp4'
Emitted 'error' event on WriteStream instance at:
    at internal/fs/streams.js:335:14
    at FSReqCallback.oncomplete (fs.js:180:23) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'D:\\hahow-video-downloader-main\\課程.mp4'
}

----------------------------------------------------------------------------------------------

測試了一下 目前下載到後面會有錯誤情況發生  Node.js是14.17.0版

**Comment by xheiop** [comment]
已修复

**Comment by SianGe** [comment]
开始下载:1-1-建置開發環境 | Python 與 Anaconda 的安裝與設定.mp4
events.js:377
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open 'D:\Downloads\hahow-video-downloader-1.0.2_2\hahow-video-downloader-1.0.2\Python 入門特訓 - 基礎實作到證照攻略\1-1-建置開發環境 | Python 與 Anaconda 的安裝與設定.mp4'
Emitted 'error' event on WriteStream instance at:
    at internal/fs/streams.js:335:14
    at FSReqCallback.oncomplete (fs.js:180:23) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'D:\\Downloads\\hahow-video-downloader-1.0.2_2\\hahow-video-downloader-1.0.2\\Python 入門特訓 - 基礎實作到證照攻略\\1-1-建置開發環境 | Python 與 Anaconda 的安裝與設定.mp4'
}

Node.js 14.17.0到14.17.6都試過 其他課程都可以下載唯獨這個Python課程不行

**Comment by xheiop** [comment]
> Node.js 14.17.0到14.17.6都試過 其他課程都可以下載唯獨這個Python課程不行

每次都是这个文件下载的时候报错么

**Comment by SianGe** [comment]
對沒錯 其他課程都不會唯獨這個 我換1-2、1-3的URL也不行

**Comment by KKgeorge** [comment]
請問這怎麼用?

**Comment by Jeffrey0117** [comment]
[hahow-collecter](https://github.com/Jeffrey0117/hahow-collecter)
上面這個連結可以用，喜歡的記得給星星，
也歡迎打賞XD
