### ISSUE TITLE
也是無法下載影片

### ISSUE THREAD

**Issue by WinnieHappyOrg** [techmovie/hahow-video-downloader#4]
錯誤訊息如下，似乎跟前一個issue的網友一樣問題，再請幫忙!謝喔  
node版本 v14.17.0

开始下载:1-1-速解學習指南 | 還在迷惘要學什麼嗎？.mp4
events.js:353
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open 'C:\Users\XXX\Downloads\hahow-video-downloader-main\一小時光屋 - 魔術方塊速解高手之路\1-1-速解學習指南 | 還在迷惘要學什麼嗎？.mp4'
Emitted 'error' event on WriteStream instance at:
    at internal/fs/streams.js:335:14
    at FSReqCallback.oncomplete (fs.js:180:23) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Users\\XXX\\Downloads\\hahow-video-downloader-main\\一小時光屋 - 魔術方塊速解高手之路\\1-1-速解學習指南 | 還在迷惘要學什麼嗎？.mp4'
}

**Comment by WinnieHappyOrg** [comment]
抱歉,我發現這是windows下執行會有的錯誤.在mac下ok.應該是跟檔名有關.windows對於檔名比較在意一些關鍵字.mac下是正常的
謝喔
